# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-08 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('district', models.CharField(max_length=255, verbose_name='区/县')),
                ('location', models.CharField(default='', max_length=255, verbose_name='详细地址')),
                ('cinema_name', models.CharField(default='', max_length=255, verbose_name='电影院名')),
                ('meituan_url', models.URLField(default='', verbose_name='美团地址')),
                ('time_url', models.URLField(default='', verbose_name='时光地址')),
                ('taopp_url', models.URLField(default='', verbose_name='淘票票地址')),
                ('nuomi_url', models.URLField(default='', verbose_name='糯米地址')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('view_count', models.IntegerField(default=0, verbose_name='访问次数')),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='cover', max_length=100, verbose_name='封面名')),
                ('cover_img', models.ImageField(default='cover/default.jpg', upload_to='cover/', verbose_name='封面图片')),
                ('is_alive', models.BooleanField(default=False, verbose_name='正在使用')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='电影名')),
                ('rating', models.FloatField(default=0, verbose_name='评分')),
                ('poster', models.ImageField(upload_to='poster/', verbose_name='海报')),
                ('WordCloud', models.ImageField(upload_to='wordcloud/', verbose_name='词云图')),
                ('trailer', models.FileField(null=True, upload_to='trailer/', verbose_name='豆瓣预告片地址')),
                ('directors', models.CharField(default='', max_length=255, verbose_name='导演')),
                ('casts', models.CharField(default='', max_length=255, verbose_name='演员')),
                ('genes', models.CharField(default='', max_length=255, verbose_name='类型')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否评分最高')),
                ('is_in_theater', models.BooleanField(default=True, verbose_name='正在上映')),
            ],
        ),
    ]
